src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('study.urls')),
    path('recommender/', include('recommender.urls')),
]

# for shoing url of images
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recommender/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import *


app_name='recommender'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name="recommender/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="recommender:login"), name='logout'),
    path('register/', views.register, name='register'),
    path('users/', views.users_view, name='users_list'),
    path('online_users/', UserListView.as_view(), name='online_users_list'),
    path('generate_users/', views.generate_users, name='generate_users'),
    path('items/', views.items_view, name='items_list'),
    path('genres/', GenreListView.as_view(), name='genres_list'),
    path('create_genre/', GenreCreateView.as_view(), name='genre_create'),
    path('genres/<int:id>/', GenreDetailView.as_view(), name='genre_detail'),
    path('genres/<int:pk>/update/', GenreUpdateView.as_view(), name='genre_update'),
    path('genres/<int:pk>/delete/', GenreDeleteView.as_view(), name='genre_delete'),
    path('ratings/', views.ratings_view, name='ratings_list'),
    path('ratings_online_users/', views.ratings_online_users, name='ratings_online_users_list'),
    path('studies/', StudyListView.as_view(), name='studies_list'),
    path('new_study/', StudyCreateView.as_view(), name='study_create'),
    path('active_study/', views.study_active_view, name='study_active'),
    path('studies/<int:id>/', StudyDetailView.as_view(), name='study_detail'),
    path('studies/<int:pk>/update/', StudyUpdateView.as_view(), name='study_update'),
    path('studies/<int:pk>/delete/', StudyDeleteView.as_view(), name='study_delete'),
    path('datasets/', DatasetListView.as_view(), name='datasets_list'),
    path('create_dataset/', DatasetCreateView.as_view(), name='dataset_create'),
    path('datasets/<int:id>/', DatasetDetailView.as_view(), name='dataset_detail'),
    path('datasets/<int:pk>/update/', DatasetUpdateView.as_view(), name='dataset_update'),
    path('datasets/<int:pk>/delete/', DatasetDeleteView.as_view(), name='dataset_delete'),
    path('uploads/', views.upload_central, name='upload_central'),
    path('movie_upload/', views.movie_upload, name='movie_upload'),
    path('rating_upload/', views.rating_upload, name='rating_upload'),
    path('link_upload/', views.link_upload, name='link_upload'),
    path('movie_upload_100K/', views.movie_upload_100K, name='movie_upload_100K'),
    path('rating_upload_100K/', views.rating_upload_100K, name='rating_upload_100K'),
    path('movie_upload_1M_10M/', views.movie_upload_1M_10M, name='movie_upload_1M_10M'),
    path('rating_upload_1M_10M/', views.rating_upload_1M_10M, name='rating_upload_1M_10M'),
    path('surprise_crossvalidate/', views.surprise_crossvalidate, name='surprise_crossvalidate'),
    path('crossvalidations_table/', views.crossvalidations_table_view, name='crossvalidations_table'),
    path('surprise_reclists/', views.surprise_predict, name='surprise_predict'),
    path('existing_reclists/', views.reclists_existing, name='reclists_existing'),
    path('all_reclists/', ReclistListView.as_view(), name='reclists_all'),
    path('reclists/', views.reclist_view, name='reclists'),
    path('reclists/<int:pk>/', ReclistDetailView.as_view(), name='reclist_detail'),
    path('evaluations/', EvaluationListView.as_view(), name='evaluations_list'),
    path('evaluations_table/', views.evaluations_table_view, name='evaluations_table'),
    path('evaluations/<int:id>/', EvaluationDetailView.as_view(), name='evaluation_detail'),
    path('algorithms/', AlgorithmListView.as_view(), name='algorithms_list'),
    path('create_algorithm/', AlgorithmCreateView.as_view(), name='algo_create'),
    path('algorithms/<int:id>/', AlgorithmDetailView.as_view(), name='algo_detail'),
    path('algorithms/<int:pk>/update/', AlgorithmUpdateView.as_view(), name='algo_update'),
    path('algorithms/<int:pk>/delete/', AlgorithmDeleteView.as_view(), name='algo_delete'),
    path('tokens/', TokenListView.as_view(), name='tokens_list'),
    path('generate_tokens/', views.generate_tokens, name='generate_token'),
    path('create_token/', TokenCreateView.as_view(), name='create_token'),
    path('create_tokens/', views.create_tokens, name='create_tokens'),
    path('tokens/<int:id>/', TokenDetailView.as_view(), name='token_detail'),
    path('tokens/<int:pk>/delete/', TokenDeleteView.as_view(), name='token_delete'),
]

src/study/urls.py
from django.urls import path
from . import views
from .views import *

app_name='study'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('start/', views.start_view, name='start'),
    path('rating/<int:id>/', views.item_rating_view, name='rating_detail'),
    path('reclist_rating/', views.reclist_view, name='reclist_rating'),
    path('reclist_rating/<int:id>/', views.reclist_rating_view, name='reclist_rating_detail'),
    path('stop/', views.stop_view, name='stop'),

]

src/recommender/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from django.views import View
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User as DjUser
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Avg
from .models import *
from .forms import *
from django.forms import formset_factory

import os, csv, io, secrets

from collections import defaultdict
from surprise import Reader, Dataset as SurDataset
from surprise.model_selection import cross_validate
from surprise import SVD, SVDpp, SlopeOne, NMF, NormalPredictor
from surprise import KNNBaseline, KNNBasic, KNNWithMeans
from surprise import BaselineOnly, CoClustering


#####################
# HOME REGISTER
#####################

# function based view
def home_view(request, *args, **kwargs):
	return render(request, "recommender/home.html", {})

def register(request, *args, **kwargs):
	if request.method == "POST":
		# get entries from the django built-in UserCreationForm in template
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get("username")
			messages.success(request, f'Account created for {username}!')
			return redirect("recommender:home")
	else:
		# instantiate the empty django built-in UserCreationForm in template
		form = UserCreationForm()
	return render(request, "recommender/register.html", {'form': form})


#####################
# TOKEN VIEWS
#####################

# class based view
class TokenListView(ListView):
	template_name = "recommender/token_list.html"
	queryset = Token.objects.all().order_by("id")


# not used, just for deleting tokens
class TokenDetailView(DetailView):
	template_name = "recommender/token_detail.html"
	queryset = Token.objects.all()

	def get_object(self):
		id = self.kwargs.get("id")
		return get_object_or_404(Token, id=id)


@method_decorator(login_required, name="dispatch")
class TokenCreateView(CreateView):
	template_name = "recommender/token_create.html"
	form_class = TokenForm
	queryset = Token.objects.all()

	def form_valid(self, form):
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("recommender:tokens_list")


@method_decorator(login_required, name="dispatch")
class TokenDeleteView(DeleteView):
	template_name = "recommender/token_delete.html"
	queryset = Token.objects.all()

	def get_success_url(self):
		return reverse("recommender:tokens_list")


@login_required
def create_tokens(request, *args, **kwargs):
	# instantiate ten empty forms in template
	TokenFormSet = formset_factory(TokenForm, extra=10)
	if request.method == 'POST':
		# get data from forms in template
		formset = TokenFormSet(request.POST, request.FILES)
		if formset.is_valid():
			for form in formset:
				if form.is_valid() and form.cleaned_data != {}:
					form.save()
			return redirect("recommender:tokens_list")
	else:
		# instantiate empty form in template
		formset = TokenFormSet()
	return render(request, 'recommender/tokens_create.html', {'formset': formset})


@login_required
def generate_tokens(request, *args, **kwargs):
	if(request.GET.get("token_btn")):
		# get data from form in template
		# entry: how many tokens
		often = (int(request.GET.get('how_many')))
		for i in range(often):
			# generate secure random numbers, eight-part
			tok = (''.join([secrets.choice('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890') for i in range(8)]))
			# create and save token to database
			Token.objects.create(name=tok)
		return redirect("recommender:tokens_list")
	return render(request, 'recommender/token_generate.html', {})


#####################
# ALGORITHM VIEWS
#####################

class AlgorithmListView(ListView):
	template_name = "recommender/algorithm_list.html"
	queryset = Algorithm.objects.all().order_by("name")


class AlgorithmDetailView(DetailView):
	template_name = "recommender/algorithm_detail.html"
	queryset = Algorithm.objects.all()

	def get_object(self):
		id = self.kwargs.get("id")
		return get_object_or_404(Algorithm, id=id)


@method_decorator(login_required, name="dispatch")
class AlgorithmCreateView(CreateView):
	template_name = "recommender/algorithm_create.html"
	form_class = AlgorithmForm
	queryset = Algorithm.objects.all()

	def form_valid(self, form):
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("recommender:algorithms_list")


@method_decorator(login_required, name="dispatch")
class AlgorithmUpdateView(UpdateView):
	template_name = "recommender/algorithm_create.html"
	form_class = AlgorithmForm
	queryset = Algorithm.objects.all()

	def form_valid(self, form):
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("recommender:algorithms_list")


@method_decorator(login_required, name="dispatch")
class AlgorithmDeleteView(DeleteView):
	template_name = "recommender/algorithm_delete.html"
	queryset = Algorithm.objects.all()

	def get_success_url(self):
		return reverse("recommender:algorithms_list")


#####################
# GENRE VIEWS
#####################


class GenreListView(ListView):
	template_name = "recommender/genre_list.html"
	queryset = MovieGenre.objects.all().order_by("title")


class GenreDetailView(DetailView):
	template_name = "recommender/genre_detail.html"
	queryset = MovieGenre.objects.all()

	def get_object(self):
		id = self.kwargs.get("id")
		return get_object_or_404(Algorithm, id=id)


@method_decorator(login_required, name="dispatch")
class GenreCreateView(CreateView):
	template_name = "recommender/genre_create.html"
	form_class = GenreForm
	queryset = MovieGenre.objects.all()

	def form_valid(self, form):
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("recommender:genres_list")


@method_decorator(login_required, name="dispatch")
class GenreUpdateView(UpdateView):
	template_name = "recommender/genre_create.html"
	form_class = GenreForm
	queryset = MovieGenre.objects.all()

	def form_valid(self, form):
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("recommender:genres_list")


@method_decorator(login_required, name="dispatch")
class GenreDeleteView(DeleteView):
	template_name = "recommender/genre_delete.html"
	queryset = MovieGenre.objects.all()

	def get_success_url(self):
		return reverse("recommender:genres_list")


#####################
# STUDY VIEWS
#####################


class StudyListView(ListView):
	template_name = "recommender/study_list.html"
	queryset = Study.objects.all().order_by("id")


class StudyDetailView(DetailView):
	template_name = "recommender/study_detail.html"
	queryset = Study.objects.all()

	def get_object(self):
		my_id = self.kwargs.get("id")
		return get_object_or_404(Study, id=my_id)


@method_decorator(login_required, name="dispatch")
class StudyCreateView(CreateView):
	template_name = "recommender/study_create.html"
	form_class = StudyForm
	queryset = Study.objects.all()

	def form_valid(self, form):
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("recommender:studies_list")


@method_decorator(login_required, name="dispatch")
class StudyUpdateView(UpdateView):
	template_name = "recommender/study_create.html"
	form_class = StudyForm
	queryset = Study.objects.all()

	def form_valid(self, form):
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("recommender:studies_list")


@method_decorator(login_required, name="dispatch")
class StudyDeleteView(DeleteView):
	template_name = "recommender/study_delete.html"
	queryset = Study.objects.all()

	def get_success_url(self):
		return reverse("recommender:studies_list")


@login_required
def study_active_view(request, *args, **kwargs):
	# instantiate empty form in template
	form = StudyFilterForm()
	# context, hand form over to template
	context = {
		'form': form,
	}
	if request.method == "POST":
		# get entry from form in template, choose study
		form = StudyFilterForm(request.POST)

		if form.is_valid():
			# get chosen study and set it on true, save changes
			study = form.cleaned_data['study']
			study.active = True
			study.save()

			# context, hand study and form over to template
			context = {
				'study': study,
				'form': form,
			}
			return render(request, "recommender/study_active.html", context)

	return render(request, "recommender/study_active.html", context)



#####################
# DATASET VIEWS
#####################


class DatasetListView(ListView):
	template_name = "recommender/dataset_list.html"
	queryset = Dataset.objects.all().order_by("id")


class DatasetDetailView(DetailView):
	template_name = "recommender/dataset_detail.html"
	queryset = Dataset.objects.all()

	def get_object(self):
		id = self.kwargs.get("id")
		return get_object_or_404(Dataset, id=id)


@method_decorator(login_required, name="dispatch")
class DatasetCreateView(CreateView):
	template_name = "recommender/dataset_create.html"
	form_class = DatasetForm
	queryset = Dataset.objects.all()

	def form_valid(self, form):
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("recommender:datasets_list")


@method_decorator(login_required, name="dispatch")
class DatasetUpdateView(UpdateView):
	template_name = "recommender/dataset_create.html"
	form_class = DatasetForm
	queryset = Dataset.objects.all()

	def form_valid(self, form):
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("recommender:datasets_list")


@method_decorator(login_required, name="dispatch")
class DatasetDeleteView(DeleteView):
	template_name = "recommender/dataset_delete.html"
	queryset = Dataset.objects.all()

	def get_success_url(self):
		return reverse("recommender:datasets_list")

src/recommender/templates/recommender/algorithm_delete.html
{% extends 'recommender/base.html' %}

{% block content %}

<form action="." method="POST"> {% csrf_token %}
  <h1>Do you really want to delete the algorithm "{{ object.name }}"?</h1>
  <br>
  <div class="col-10">
	   <div class="text-right">
	      <p>
          <a href="{% url 'recommender:algorithms_list' %}" class="btn btn-primary">Cancel</a>
          <input type="submit" class="btn btn-info" name="" value="Yes" />
        </p>
      </div>
  </div>
</form>

{% endblock %}

src/recommender/templates/recommender/algorithm_list.html
{% extends 'recommender/base.html' %}

{% block content %}

<h1>Algorithms</h1>

<br>

{% for instance in object_list %}
	<div class="large row">
		<div class="col-5">
			<a href="{{ instance.get_absolute_url }}">{{ instance.name }}</a>
		</div>
		<div>
			<a class="btn btn-info" href="{{ instance.get_absolute_url }}update" role="button">Update</a>
			<a class="btn btn-warning" href="{{ instance.get_absolute_url }}delete" role="button">Delete</a>
		</div>
	</div>
{% endfor %}

{% endblock %}

src/recommender/templates/recommender/crossvalidations_table.html
{% extends 'recommender/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<h1>Accuracy metrics </h1>
<h3>(from 5-fold cross-validation, per dataset, ordered by RMSE ascending)</h3>

<br><br>

<div class="row">
	<div class="col-6">
		<form method="POST"> {% csrf_token %}
			<h1>Choose dataset:</h1>

			{{ form|crispy }}

			<div class="text-right">
				<a href="{% url 'recommender:surprise_crossvalidate' %}" class="btn btn-primary" role="button">Cancel</a>
				<input type="submit" class="btn btn-info" value="Choose" />
			</div>
		</form>
	</div>
</div>

{% if study %}
	<br><br>
	<h2>The 5-fold crossvalidations for dataset {{ datset }} are:</h2>
	<br>
{% endif %}

{% if crossvalidations %}
	<div class="row">
		<div class="col-md mt-3 mb-3">
			<table class="table table-striped table-bordered">
			  <thead>
			    <tr>
			      <th scope="col"></th>
						<th scope="col">Algorithm</th>
						<th scope="col">RMSE</th>
						<th scope="col">MAE</th>
						<th scope="col">Fit time</th>
						<th scope="col">Test time</th>
			    </tr>
			  </thead>
			  <tbody>
					{% for object in crossvalidations %}
						<tr>
				      <th scope="row">{{ forloop.counter }}</th>
							<td>{{ object.algorithm }}</td>
							<td>{{ object.rmse }}</td>
							<td>{{ object.mae }}</td>
							<td>{{ object.fit_time }}</td>
							<td>{{ object.test_time }}</td>
				    </tr>
					{% endfor %}
			  </tbody>
			</table>

			<div class="text-right">
				<a href="{% url 'recommender:surprise_crossvalidate' %}" role="button" class="btn btn-info" >Next cross-validation</a>
				<a href="{% url 'recommender:home' %}" role="button" class="btn btn-info" >Home</a>
			</div>
		</div>
	</div>
{% endif %}

{% endblock %}

src/recommender/templates/recommender/dataset_detail.html
{% extends 'recommender/base.html' %}

{% block content %}

<div class="col-md-12 mt-3 mb-3">
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th scope="col"></th>
	      <th scope="col"></th>
	    </tr>
	  </thead>
	  <tbody>
		<tr>
	      <th scope="row">Name</th>
	      <td>{{ object.name }}</td>
	    </tr>
	    <tr>
	      <th scope="row">Size</th>
	      <td>{{ object.size }}</td>
	    </tr>
			<tr>
		     <th scope="row">Category</th>
		     <td>{{ object.category }}</td>
		  </tr>
			<tr>
	      <th scope="row">Description</th>
	      <td>{{ object.description }}</td>
	    </tr>
	  </tbody>
	</table>

	<br>

	<div class="col-10">
		<div class="text-right">
			<p>
				<a href="{% url 'recommender:datasets_list' %}" class="btn btn-info" >Back to List</a>
			</p>
		</div>
	</div>
</div>

{% endblock %}

src/recommender/templates/recommender/evaluation_detail.html
{% extends 'recommender/base.html' %}

{% block content %}

<div class="row">
	<div class="col-md mt-3 mb-3">
		<table class="table table-bordered">
		  <thead>
		    <tr>
		      <th scope="col"></th>
					<th scope="col">ID</th>
		      <th scope="col">Study</th>
					<th scope="col">Online user</th>
					<th scope="col">Utility</th>
					<th scope="col">Serendipity</th>
					<th scope="col">Novelty</th>
					<th scope="col">Diversity</th>
					<th scope="col">Unexpectedness</th>
					<th scope="col">MAE</th>
					<th scope="col">MSE</th>
					<th scope="col">RMSE</th>
					<th scope="col">Not Rated</th>
		    </tr>
		  </thead>
		  <tbody>
			<tr>
		      <th scope="row"></th>
					<td>{{ object.id }}</td>
		      <td>{{ object.study }}</td>
					<td>{{ object.user }}</td>
					<td>{{ object.utility }}</td>
					<td>{{ object.serendipity }}</td>
					<td>{{ object.novelty }}</td>
					<td>{{ object.diversity }}</td>
					<td>{{ object.unexpectedness }}</td>
					<td>{{ object.accuracy_mae }}</td>
					<td>{{ object.accuracy_mse }}</td>
					<td>{{ object.accuracy_rmse }}</td>
					<td>{{ object.non_rating_rate }}</td>
		    </tr>
		  </tbody>
		</table>

		<div class="text-right">
			<p>
				<a href="{% url 'recommender:evaluations_table' %}" class="btn btn-info" >Back to Table</a>
				<a href="{% url 'recommender:evaluations_list' %}" class="btn btn-info" >Back to List</a>
			</p>
		</div>
	</div>
</div>

{% endblock %}

src/recommender/templates/recommender/evaluations_list.html
{% extends 'recommender/base.html' %}

{% block content %}

	<h1>Ratings of recommendation lists</h1>

	<br>

	{% for instance in object_list %}
		<div class="row">
			<div class="col-md-2">
				<h2><a href="{{ instance.get_absolute_url }}">{{ instance.id }}</a></h2>
			</div>

			<div class="col-md-4 mt-3 mb-3">
				<table class="table table-striped">
			  	<thead>
			    	<tr>
			      	<th scope="col"></th>
			      	<th scope="col"></th>
			    	</tr>
			  	</thead>
			  	<tbody>
						<tr>
				      <th scope="row">Study</th>
				      <td>{{ instance.study }}</td>
				    </tr>
				    <tr>
				      <th scope="row">User</th>
				      <td>{{ instance.user }}</td>
				    </tr>
				  </tbody>
				</table>
			</div>
		</div>
	{% endfor %}

{% endblock %}

src/recommender/templates/recommender/genre_delete.html
{% extends 'recommender/base.html' %}

{% block content %}

<div class="large container">
  <div class="row">
    <div class="col-8">
      <form action="." method="POST"> {% csrf_token %}
        <h1>Do you really want to delete the genre "{{ object.title }}"?</h1>

        <br>

        <div class="text-right">
  	       <p>
             <a href="{% url 'recommender:genres_list' %}" class="btn btn-primary">Cancel</a>
             <input type="submit" class="btn btn-info" name="" value="Yes" />
           </p>
         </div>
       </form>
     </div>
  </div>
</div>

{% endblock %}

src/recommender/templates/recommender/genre_detail.html
{% extends 'recommender/base.html' %}

{% block content %}

	<p>{{ object.id }} </p>
	<p>{{ object.title }} </p>

	<br>
	
	<p><a href="{% url 'recommender:genres_list' %}" class="btn btn-primary" >Back to List</a></p>

{% endblock %}

src/recommender/templates/recommender/genre_list.html
{% extends 'recommender/base.html' %}

{% block content %}

	<div class="large container">
		<h1>Genres</h1>

		<br>

		{% for instance in object_list %}
			<div class="row">
				<div class="col-5">
					{{ instance.title }}
				</div>
				<div>
					<a class="btn btn-info" href="{{ instance.get_absolute_url }}update" role="button">Update</a>
					<a class="btn btn-warning" href="{{ instance.get_absolute_url }}delete" role="button">Delete</a>
				</div>
			</div>
		{% endfor %}
	</div>

{% endblock %}

src/recommender/templates/recommender/register.html
{% extends 'recommender/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="content-section">
  <div class="row">
    <div class="col-6">
      <form method="POST"> {% csrf_token %}
        <fieldset>
          <legend class="border-bottom mb-4">Register now</legend>

            {{ form|crispy }}

        </fieldset>
        <div class="text-right">
          <button class="btn btn-outline-info" type="submit" name="button">Sign Up</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

src/recommender/templates/recommender/surprise_crossvalidate.html
{% extends 'recommender/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<h1>5-fold cross-validation:</h1>
<h3>compute the MAE and RMSE of algorithms for various datasets</h3>

<br><br>

{% if messages %}
	{% for message in messages %}
		<div>
			<strong>{{message|safe}}</strong>
		</div>
	{% endfor %}
{% endif %}

<div class="row">
	<div class="col-6">
		<form method="POST"> {% csrf_token %}

			{{ d_form|crispy }}
			{{ a_form|crispy }}

			<br>

			{{ f_form|crispy }}

			<br>

			<div class="text-right">
		  	<input type="submit" class="btn btn-info" value="Cross-validate" name="surprise_btn">
			</div>
		</form>
	</div>
</div>

{% endblock %}

src/recommender/templates/recommender/token_create.html
{% extends 'recommender/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="row">
  <div class="col-6">
    <form method="POST"> {% csrf_token %}

      {{ form|crispy }}

      <a href="{{ view.get_success_url }}" class="btn btn-primary" role="button">Cancel</a>
      <input type="submit" class="btn btn-success" name="" value="Save" />
    </form>
  </div>
</div>

{% endblock %}

src/recommender/templates/recommender/upload.html
{% extends 'recommender/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<h1>{{ title }}</h1>

{% if messages %}
	{% for message in messages %}
		<div>
			<strong>{{message|safe}}</strong>
		</div>
	{% endfor %}
{% else %}
	<form method="POST"> {% csrf_token %}
		<h2 class="text-info">Choose dataset</h2>
		<h5>{{ example }}</h5>
		<br>
		<div class="row">
			<div class="col-6">

				{{ form|crispy }}

				<div class="text-right">
					<a href="{{ view.get_success_url }}" class="btn btn-primary" role="button">Cancel</a>
					<input type="submit" class="btn btn-info" value="Choose" name="dataset_btn" />
				</div>
			</div>
		</div>
	</form>

	<br><br>

	{% if dataset %}
		<h1>Chosen dataset is {{ dataset }}</h1>
	{% endif %}

	<br><br>

	<strong>{{ order }}</strong>

	<br><br>

	<form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
		<label for="file1"> Upload a file</label>
		<input type="file" id="file1" name="file">
		<small>Only accepts CSV files</small>
		<button type="submit" class="btn btn-primary" name="upload">Upload</button>
	</form>
{% endif %}

{% endblock %}

src/recommender/templates/recommender/users.html
{% extends 'recommender/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="row">
	<div class="col-6">
		<form method="POST"> {% csrf_token %}
			<h1>Choose dataset</h1>

			{{ form|crispy }}

			<div class="text-right">
				<a href="{{ view.get_success_url }}" class="btn btn-primary" role="button">Cancel</a>
				<input type="submit" class="btn btn-info" value="Choose" />
			</div>
		</form>

		<div class="container mt-3 mb-3">
			{% if users %}
				<p>The dataset {{ dataset }} has {{ amount }} users.</p>
			{% endif %}

			<ul>
				{% for user in users %}
					<li>User ID: {{user.user_id}} 	Dataset: {{user.dataset}} </li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>

{% endblock %}