src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('study.urls')),
    path('recommender/', include('recommender.urls')),
]

# for shoing url of images
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/study/urls.py
from django.urls import path
from . import views
from .views import *

app_name='study'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('start/', views.start_view, name='start'),
    path('rating/<int:id>/', views.item_rating_view, name='rating_detail'),
    path('reclist_rating/', views.reclist_view, name='reclist_rating'),
    path('reclist_rating/<int:id>/', views.reclist_rating_view, name='reclist_rating_detail'),
    path('stop/', views.stop_view, name='stop'),

]

src/recommender/models.py
from django.db import models, transaction
from django.urls import reverse

# Create your models here.
class MovieGenre(models.Model):
	title = models.CharField(max_length=100, null=False, unique=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("recommender:genre_detail", kwargs={"id": self.id})

class Algorithm(models.Model):
	name = models.CharField(max_length=100, null=False, unique=True)
	description = models.TextField(blank=True, null=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("recommender:algo_detail", kwargs={"id": self.id})


class Dataset(models.Model):
	name = models.CharField(max_length=200, unique=True)
	size = models.PositiveIntegerField()
	category = models.CharField(max_length=200)
	description = models.TextField(blank=True, null=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("recommender:dataset_detail", kwargs={"id": self.id})


class Crossvalidation(models.Model):
	algorithm = models.ForeignKey('Algorithm', on_delete=models.CASCADE)
	dataset = models.ForeignKey('Dataset', on_delete=models.CASCADE)
	rmse = models.DecimalField(max_digits=12, decimal_places=10, null=True)
	mae = models.DecimalField(max_digits=12, decimal_places=10, null=True)
	fit_time = models.DecimalField(max_digits=20, decimal_places=4, null=True)
	test_time = models.DecimalField(max_digits=20, decimal_places=4, null=True)


class Token(models.Model):
	name = models.CharField(max_length=40, blank=False, null=False, unique=True)
	valid = models.BooleanField(default=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("recommender:token_detail", kwargs={"id": self.id})


class User(models.Model):
	user_id = models.PositiveIntegerField(null=True)
	name = models.CharField(max_length=200, null=True)
	account = models.CharField(max_length=200, null=True, unique=True)
	token = models.OneToOneField('Token', on_delete=models.CASCADE, blank=True, null=True)
	online_user = models.BooleanField(default=False)
	dataset = models.ForeignKey('Dataset', on_delete=models.CASCADE, blank=True, null=True)

	def __str__(self):
		if self.token != None:
			return self.token.name
		else:
			return str(self.user_id)+ " of Dataset " + str(self.dataset)

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['user_id', 'dataset'], name='unique_user_ds2')
		]

class Item(models.Model):
	item_id = models.PositiveIntegerField(null=True)
	name = models.CharField(max_length=200)
	dataset = models.ForeignKey('Dataset', on_delete=models.CASCADE)
	genres = models.ManyToManyField('MovieGenre', related_name='items')
	imdb_id = models.PositiveIntegerField(null=True)
	amount_ratings = models.PositiveIntegerField(null=True, blank=True)
	poster = models.ImageField(upload_to = 'posters', height_field=None, width_field=None, max_length=200, null=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("study:rating_detail", kwargs={"id": self.id})

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['item_id', 'dataset'], name='unique_item_ds2')
		]

class Rating(models.Model):
	user = models.ForeignKey('User', on_delete=models.CASCADE)
	item = models.ForeignKey('Item', on_delete=models.CASCADE)
	rating = models.DecimalField(max_digits=10, decimal_places=2)

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['user', 'item'], name='unique_rating2')
		]


class Reclist(models.Model):
	user = models.ForeignKey('User', on_delete=models.CASCADE)
	algorithm = models.ForeignKey('Algorithm', on_delete=models.CASCADE)
	length = models.PositiveSmallIntegerField()
	items = models.ManyToManyField('Item', through='ReclistItem', related_name='reclists')

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['user', 'algorithm', 'length'], name='unique_recl_user2')
		]

	def get_absolute_url(self):
		return reverse("recommender:reclist_detail", kwargs={"id": self.id})

class ReclistItem(models.Model):
	reclist = models.ForeignKey('Reclist', on_delete=models.CASCADE, related_name='reclist_items')
	item = models.ForeignKey('Item', on_delete=models.CASCADE, related_name='reclist_items')
	prediction = models.DecimalField(max_digits=20, decimal_places=10)
	number = models.PositiveIntegerField()

	class Meta:
		ordering = ('number',)

class Evaluation(models.Model):
	study = models.ForeignKey('Study', on_delete=models.CASCADE)
	reclist = models.ForeignKey('Reclist', on_delete=models.CASCADE)
	user = models.ForeignKey('User', on_delete=models.CASCADE)
	accuracy_mae = models.DecimalField(max_digits=10, decimal_places=2, null=True)
	accuracy_mse = models.DecimalField(max_digits=10, decimal_places=2, null=True)
	accuracy_rmse = models.DecimalField(max_digits=10, decimal_places=2, null=True)
	non_rating_rate = models.DecimalField(max_digits=10, decimal_places=2, null=True)
	utility = models.DecimalField(max_digits=10, decimal_places=2, null=True)
	serendipity = models.DecimalField(max_digits=10, decimal_places=2, null=True)
	novelty = models.DecimalField(max_digits=10, decimal_places=2, null=True)
	diversity = models.DecimalField(max_digits=10, decimal_places=2, null=True)
	unexpectedness = models.DecimalField(max_digits=10, decimal_places=2, null=True)

	class Meta:
		constraints = [
			models.UniqueConstraint(fields=['study', 'reclist', 'user'], name='unique_study_eval')
		]

	def get_absolute_url(self):
		return reverse("recommender:evaluation_detail", kwargs={"id": self.id})

class Study(models.Model):
	name = models.CharField(max_length=200, unique=True)
	dataset = models.ForeignKey('Dataset', on_delete=models.CASCADE)
	description = models.TextField(blank=True, null=True)
	active = models.BooleanField(default=False)
	algorithms = models.ManyToManyField('Algorithm', related_name='studies')
	reclist_length = models.PositiveSmallIntegerField()

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("recommender:study_detail", kwargs={"id": self.id})

	def save(self, *args, **kwargs):
		if not self.active:
			return super(Study, self).save(*args, **kwargs)
		with transaction.atomic():
			Study.objects.filter(active=True).update(active=False)
			return super(Study, self).save(*args, **kwargs)

src/study/models.py
from django.db import models

# Create your models here.

src/study/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.models import User as DjUser
from recommender.models import *
from .forms import RatingForm, RatingHdForm, RatingHdFormSet, EvaluationForm
from recommender.forms import UserLoginForm

import random, math




###################
# MAPPING OF USERS
###################

class Most_rated_neighbours():
	"""
	base class for Mapping
	purpose: finding the users (nr_users) which rated the most of the most rated items (nr_ratings)
	"""
	def __init__(self, online_user, nr_ratings = None, nr_users = None, dataset = None, mapped_user = None):
		self.online_user = online_user
		self.nr_ratings = nr_ratings
		self.nr_users = nr_users
		self.dataset = Study.objects.get(active=True).dataset
		self.mapped_user = mapped_user

	# help method for most_rated_items_raters
	def sortbySecond(val):
		return val[1]

	# finding the users (arg: nr_users) which rated the most of the most rated items (arg: nr_ratings)
	def most_rated_items_raters(self):
		# items of dataset of current active study
		items = Item.objects.filter(dataset=self.dataset)
		# a number, given by nr_ratings, of most_rated items (items sorted)
		most_rated = items.order_by("-amount_ratings")[:self.nr_ratings]
		my_list = []
		# for all users: count the ratings of the most rated items, save in tuple
		for user in User.objects.filter(dataset=self.dataset):
			i = 0
			for item in most_rated:
				try:
					Rating.objects.get(user=user, item=item)
					i = i + 1
					my_tuple = (user, i)
				except(Rating.DoesNotExist):
					pass
			# save tuples in list
			my_list.append(my_tuple)
		# sort list by second entry (amount ratings per user)
		my_list.sort(key = sortbySecond, reverse = True)
		# get the first number (given by nr_users) of users
		user_list = [user[0] for user in my_list[:self.nr_users]]
		# get a random user of user_list and return the user
		self.mapped_user = random.choice(user_list)
		return self.mapped_user


class Mapping(Most_rated_neighbours):
	"""
	extending class Most_rated_neighbours
	purpose: mapping the online user randomly to an offline user, included in the dataset
	"""
	def random(self):

		# count users of current dataset
		sum_user = User.objects.filter(dataset=self.dataset).count()
		if (sum_user) > 0:
			random_user_id = random.randrange(sum_user)
			# get and return a random user
			self.mapped_user = User.objects.get(dataset=self.dataset, user_id=random_user_id)
	return self.mapped_user



##########################################################
# ACCURACY FUNCTIONS FOR CALCULATION FOR THE EVALUATIONS
##########################################################

# mean absolute error
def accuracy_mae(evaluation):
	reclist = evaluation.reclist
	user = evaluation.user

	sum = 0
	i = 0
	mae = 0

	# for all items in recommendation list
	for ri in reclist.reclist_items.all():
		try:
			# get rating of online user
			user_rating = Rating.objects.get(user=user,item=ri.item).rating
			# difference between rating of online user and predicted rating of offline user
			diff = abs(user_rating - ri.prediction)
			sum = sum + diff
			i = i+1
		except (Rating.DoesNotExist):
			print("Rating does not exist")
	# return MAE
	mae = sum/i
	return mae


# mean squared error
def accuracy_mse(evaluation):
	reclist = evaluation.reclist
	user = evaluation.user

	sum = 0
	i = 0
	mse = 0

	# for all items in recommendation list
	for ri in reclist.reclist_items.all():
		try:
			# get rating of online user
			user_rating = Rating.objects.get(user=user,item=ri.item).rating
			# difference between rating of online user and predicted rating of offline user
			diff = abs(user_rating - ri.prediction)
			# difference to square
			sq_diff = math.pow(diff,2)
			sum = sum + sq_diff
			i = i+1
		except (Rating.DoesNotExist):
			print("Rating does not exist")
	# return MSE
	mse = sum/i
	return mse


# root mean squared error
def accuracy_rmse(evaluation):
	return math.sqrt(accuracy_mse(evaluation))



###########################################
# ACTUAL VIEWS
###########################################

# function based view
def home_view(request, *args, **kwargs):
	# get active study
	study = Study.objects.get(active=True)
	# context, hand over to template
	context = {
		'study': study,
	}
	return render(request, "study/home.html", context)


def login_view(request, *args, **kwargs):
	# instantiate empty form in template
	form = UserLoginForm()
	if request.method == "POST":
		# get entries from form in template
		form = UserLoginForm(request.POST)
		if form.is_valid():
			# get token by user in form field
			new_token = form.cleaned_data['token']
			# get token by entry, returns object, if exists (else 404)
			obj_token = get_object_or_404(Token, name=new_token)
			# cancel validity of token
			obj_token.valid = False
			obj_token.save()
			obj = str(obj_token)
			# create user in recommender database, as online user
			User.objects.create(token=obj_token,online_user=True)
			# create Django user (username is his token) and login
			object = DjUser.objects.create(username=obj)
			login(request, object)

			return redirect("study:start")
	else:
		# instantiate empty form in template
		form = UserLoginForm()
	return render(request, 'study/login.html', {'form': form})


def start_view(request, *args, **kwargs):
	if not request.user.is_authenticated:
		messages.warning(request, 'You need to be authenticated.')
		return redirect('study:login')
	# user is logged in
	else:
		# get token by django username and user by token
		token_obj = Token.objects.get(name=request.user.username)
		user_obj = User.objects.get(token=token_obj)
		# empty set
		reclists = set()
		algos = []
		# get active study
		study = Study.objects.get(active=True)
		# get all algorithms to be compared in the study and save in list (algos)
		algo_query = study.algorithms.all()
		for a in algo_query:
			algos.append(a)
		# test whether evaluations for this study and user already exist in the database
		evals = Evaluation.objects.filter(study=study, user=user_obj)
		# test whether the length of algos and evals are the username
		# if yes: user already exists in study
		if (len(evals) == len(algos)):
			# add all recommendation lists that already exist in the database
			for eval in evals:
				reclists.add(eval.reclist)
		else:
			# random mapping of online user to offline user in dataset
			mapping = Mapping(user_obj)

			# Mapping variant I

			mapped_user = mapping.random()

			# Mapping variant II
			# random mapping to one of 50 offline users which rated the most of the 25 most rated items

			#mapping.nr_ratings = 25
			#mapping.nr_users = 50
			#mapped_user = mapping.most_rated_items_raters()

			try:
				for i in range(len(algos)):
					# try to get the recommendation list of mapped user and desired algorithm and list length
					rl_obj = Reclist.objects.get(user=mapped_user, algorithm=algos[i], length=study.reclist_length)
					# create and save evaluations for current online user, active study and found recommendation list
					Evaluation.objects.create(study=study, user=user_obj, reclist=rl_obj)
					reclists.add(rl_obj)
			# if recommendation list does not exist: warning message
			except Reclist.DoesNotExist:
				messages.warning(request, 'There seems to be a recommendation list missing. Please inform the study director.'
											' Thank you! Have lists been created for all algorithms of the study?')

		# empty set
		items = set()
		# save all items included in recommendation lists in set (to avoid duplicates)
		for reclist in reclists:
			for item in reclist.reclist_items.all():
				items.add(item.item)
		items_list = []
		# save all ids of items from set in the list
		for item in items:
			items_list.append(item.id)
		# save the list as session variable
		request.session['items_list'] = items_list
		request.session.modified = True

		# context, hand items and list of items over to template
		context = {
			"items":items,
			"items_list": request.session['items_list'],
		}
	return render(request, "study/start.html", context)


def item_rating_view(request, id, **kwargs):
	if not request.user.is_authenticated:
		messages.warning(request, 'You need to be authenticated.')
		return redirect('study:login')
	# user is logged in
	else:
		if request.method=='GET':
			# session variables runs and non_ratings, required no more in current version
			request.session['runs'] = 0
			request.session['non_ratings'] = 0
			# get user by token
			token_obj = Token.objects.get(name=request.user.username)
			user_obj = User.objects.get(token=token_obj)
			# get item by id, passed as argument in the request
			item=get_object_or_404(Item, id=id)
			# remove the first element from the list in the session variable
			request.session['items_list'].pop(0)
			request.session.modified = True
			# hand over the updated list to the template, if the list is not empty
			items_list = request.session['items_list']
			if request.session['items_list']:
				# hand items and list of items over to template
				context={
					"item":item,
					"items_list":items_list,
				}
			else:
				# hand items over to template
				context={
					"item":item,
				}
		if request.method=='POST':
			# count up runs
			request.session['runs'] = request.session['runs'] + 1

			# get entries from template form
			user = request.POST.get("user")
			item = request.POST.get("item")
			rating = request.POST.get("rating")

			ruser = User.objects.get(token=Token.objects.get(name=user))
			ritem = Item.objects.get(id=item)

			# valid rating
			if rating != "":
				try:
					# warning message, if rating for user and item already exists
					Rating.objects.get(user=ruser,item=ritem)
					messages.warning(request, 'This item has already been rated by you. Therefore the rating is not saved.')
				except(Rating.DoesNotExist):

src/study/templates/study/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	  <link rel="stylesheet" type="text/css" href="{% static 'recommender/style.css' %}">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css2?family=Literata&family=Crimson+Pro&family=Roboto'>

    <title>A Web-based Hybrid Evaluation Scheme for Recommender Systems</title>

  </head>
  <body>
		<div class="page-header py-4 bg-light">
			<div class="col-md-12 text-center">

				<h1 class="text-info">Evaluation Study for Recommender Systems</h1>

				{% include 'study/navbar_study.html' %}

			</div>
		</div>

		<div class="content container">
			<div class="col-md-12">
				{% if messages %}
					{% for message in messages %}
						<div class="alert alert-{{ message.tags }}">
							{{ message }}
						</div>
					{% endfor %}
				{% endif %}
				<div class="container mt-5 mb-5">
					{% block content %}
					{% endblock %}
				</div>
			</div>
		</div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

src/study/templates/study/home.html
{% extends 'Study/base.html' %}

{% block content %}

  <h1>Welcome to the study {{ study.name }} for evaluation of recommender systems!</h1>

  <br><br>

  <a href="{% url 'study:login' %}">Please login with your valid token</a>

{% endblock %}

src/study/templates/study/login.html
{% extends 'study/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
  <form method="POST"> {% csrf_token %}
    <legend class="border-bottom mb-4">Please login with your valid token:</legend>
    <div class="row">
      <div class="col-6">
        {{ form|crispy }}
        <div class="text-right">
          <input type="submit" class="btn btn-info" value="Login" />
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

src/study/templates/study/navbar_study.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand text-info" href="{% url 'study:home' %}">Evaluation Study</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-info" href="{% url 'study:login' %}">Login</a>
      </li>
    </ul>
  </div>
</nav>

src/study/templates/study/rating_detail.html
{% extends 'study/base.html' %}

{% block content %}

	{%if not all_rated %}
		<div class="row">
			<div class="col-md-8">
				<div class="font-italic"><h3>Please rate the following item on a scale of 1 to 10</h3></div>
				<br>

				<h2>{{ item }}</h2>
				<div class="col-md-5 mt-5">
					<div class="d-flex justify-content-around">
						{% if item.poster %}
							<img class="resize_big" src="{{ item.poster.url }}" alt="img">
							{% endif %}
						</div>
				</div>

				<br><br>

				{%if items_list %}
					<form method="POST" action="{% url 'study:rating_detail' items_list.0 %}"> {% csrf_token %}
				{% else%}
					<form method="POST" action="{% url 'study:rating_detail' item.id %}"> {% csrf_token %}
				{% endif %}

				<br>

				<div class="row">
					<div class="col-10">
						<div class="form-check form-check-inline">
  						<input class="form-check-input" required="true" type="radio" name="rating" id="0.5" value="0.5">
  						<label class="form-check-label" for="0.5">1</label>
						</div>
						<div class="form-check form-check-inline">
							<input class="form-check-input" required="true" type="radio" name="rating" id="1" value="1">
  						<label class="form-check-label" for="1">2</label>
						</div>
						<div class="form-check form-check-inline">
							<input class="form-check-input" required="true" type="radio" name="rating" id="1.5" value="1.5">
  						<label class="form-check-label" for="1.5">3</label>
						</div>
						<div class="form-check form-check-inline">
							<input class="form-check-input" required="true" type="radio" name="rating" id="2" value="2">
  						<label class="form-check-label" for="2">4</label>
						</div>
						<div class="form-check form-check-inline">
							<input class="form-check-input" required="true" type="radio" name="rating" id="2.5" value="2.5">
  						<label class="form-check-label" for="2.5">5</label>
						</div>
						<div class="form-check form-check-inline">
							<input class="form-check-input" required="true" type="radio" name="rating" id="3" value="3">
  						<label class="form-check-label" for="3">6</label>
						</div>
						<div class="form-check form-check-inline">
							<input class="form-check-input" required="true" type="radio" name="rating" id="3.5" value="3.5">
  						<label class="form-check-label" for="3.5">7</label>
						</div>
						<div class="form-check form-check-inline">
							<input class="form-check-input" required="true" type="radio" name="rating" id="4" value="4">
  						<label class="form-check-label" for="4">8</label>
						</div>
						<div class="form-check form-check-inline">
							<input class="form-check-input" required="true" type="radio" name="rating" id="4.5" value="4.5">
  						<label class="form-check-label" for="4.5">9</label>
						</div>
						<div class="form-check form-check-inline">
							<input class="form-check-input" required="true" type="radio" name="rating" id="5" value="5">
  						<label class="form-check-label" for="5">10</label>
						</div>
						<div class="form-check form-check-inline">
							<input class="form-check-input" required="true" type="radio" name="rating" id="None" value="">
  						<label class="form-check-label" for="None">Don't know</label>
						</div>
					</div>
				</div>
				<select name="user" required="" id="id_user" hidden="True">
		  		<option value="{{request.user }}" selected="{{request.user }}"></option>
				</select>
				<select name="item" required="" id="id_item" hidden="True">
		  		<option value="{{ item.id }}" selected="{{ item.id }}"></option>
				</select>

				<div class="text-right">
					<input type="submit" class="btn btn-info" value="Save" />
				</div>
			</div>
		</div>
	</form>

	{% else %}

	<br><br>

	<div class="row">
		<div class="col-md-5">
			<h1>Thank you for rating!</h1>

			<br><br>
			
			<div class="text-right">
				<a href="{% url 'study:reclist_rating' %}" class="btn btn-info">Next to the recommendation lists</a>
			</div>
		</div>
	</div>
	{% endif %}

{% endblock %}

src/study/templates/study/reclist_rating_begin.html
{% extends 'study/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
	<h1>These are the determined recommendation lists:</h1>

	<br><br>

	{% for reclist in reclists %}
		<div class="row">
			<div class="col-md-8">
				<h4><li>Recommendation list {{forloop.counter}}</li></h4>
				<ol>
				{% for ri in reclist.reclist_items.all %}
					<li>{{ ri.item }}</li>
				{% endfor %}
				</ol>
			</div>
		</div>
	{% endfor %}

	<br>

	<div class="row">
		<div class="col-md-8">
			<div class="text-right">
				<a href="{% url 'study:reclist_rating_detail' reclists_list.0 %}" class="btn btn-info">Begin rating of recommendation lists</a>
			</div>
		</div>
	</div>

{% endblock %}

src/study/templates/study/reclist_rating_detail.html
{% extends 'study/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

	{%if not all_rated %}
		<div class="font-italic"><h3>Please rate the given recommendation lists on a scale of 1 to 5</h3></div>

		<div class="row">
			<div class="col-md-6 mt-5">
				<ol>
					{% for ri in reclist.reclist_items.all %}
						<li>
								<p>{{ ri.item }}</p>
							{% if ri.item.poster %}
							<div class="col-md-5">
								<div class="d-flex justify-content-around">
									<p><img style="width: 80px; height: auto" src="{{ ri.item.poster.url }}" alt="img"></p>
								</div>
							</div>
							{% endif %}
						</li>
					{% endfor %}
				</ol>
			</div>
			<div class="co-md-6 mt-5">
				{%if reclists_list %}
					<form method="POST" action="{% url 'study:reclist_rating_detail' reclists_list.0 %}" name="{{ reclist.id }}"> {% csrf_token %}
				{% else%}
					<form method="POST" action="{% url 'study:reclist_rating_detail' reclist.id %}"> {% csrf_token %}
				{% endif %}

						<p class="font-weight-bold">How much did you enjoy the recommendations?</p>
						{% for radio in form.utility %}
							<div class="form-check form-check-inline">
    						{{ radio }}
							</div>
						{% endfor %}

						<p class="font-weight-bold">How much and pleasantly were you surprised?</p>
						{% for radio in form.serendipity %}
							<div class="form-check form-check-inline">
    						{{ radio }}
							</div>
						{% endfor %}

						<p class="font-weight-bold">How novel were the recommendations for you?</p>
						{% for radio in form.novelty %}
							<div class="form-check form-check-inline">
    						{{ radio }}
							</div>
						{% endfor %}

						<p class="font-weight-bold">How would you rate the variety of items in the recommendation list?</p>
						{% for radio in form.diversity %}
							<div class="form-check form-check-inline">
    						{{ radio }}
							</div>
						{% endfor %}

						<p class="font-weight-bold">How unexpected were the recommendations?</p>
						{% for radio in form.unexpectedness %}
							<div class="form-check form-check-inline">
    						{{ radio }}
							</div>
						{% endfor %}

						<br><br>

						<select name="reclist" required="" id="id_reclist" hidden="True">
				  	<option value="{{ reclist.id }}" selected="{{ reclist.id }}"></option>
						<div class="text-right">
							<input type="submit" class="btn btn-info" name="{{ reclist.id }}" value="Save" />
						</div>
					</form>
			</div>
		</div>

	{% else %}

	<br><br>

	<div class="row">
		<div class="col-md-5">
			<h1>Thank you for rating!</h1>

			<br><br>
			
			<div class="text-right">
				<a href="{% url 'study:stop' %}" class="btn btn-info">Finish rating</a>
			</div>
		</div>
	</div>
	{% endif %}

{% endblock %}

src/study/templates/study/start.html
{% extends 'study/base.html' %}

{% block content %}

	<div class="row">
		<div class="col-md-8">
			<h1>The determined items are:</h1>
			<br>
			<ul>
				{% for item in items %}
					<li>{{ item }} </li>
				{% endfor %}
			</ul>
			<br>
			<div class="text-center">
				<a href="{% url 'study:rating_detail' items_list.0 %}" class="btn btn-info">Begin rating</a>
			</div>
		</div>
	</div>

{% endblock %}

src/study/templates/study/stop.html
{% extends 'study/base.html' %}

{% block content %}

	<br><br>
	<h1>Thank you for participating!</h1>
	<br><br>
	
{% endblock %}